name: Generate Datas

on:
  schedule: # ejecutar cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Configuración de Node.js 16
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      # Animación de la serpiente (Snake Animation)
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: vidaldcabrera
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
